spring:
  servlet:
    multipart:
      max-file-size: 10000MB
      max-request-size: 10000MB
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/library
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
  session:
    timeout: 10m
    store-type: redis
  redis:
    host: redis #redis localhost
    port: 6379


upload:
  dir: src/main/resources/static/videos/